name: PR Bot – Fetch Diff

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fetch-pr-diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: install dependencies
        run: npm install @octokit/core

      - name: Run Fetch scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEW_API_URL: ${{ secrets.REVIEW_API_URL }}
          PR_NUMBER: ${{ github.event.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          node .github/scripts/fetch-pr-diff.js
